// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGt_9zVykXaUbEqnYJIsaiIaqUimNnno',
    appId: '1:16582216303:web:cb74475804c83c7d045b9a',
    messagingSenderId: '16582216303',
    projectId: 'busarrivalalrammonitor',
    authDomain: 'busarrivalalrammonitor.firebaseapp.com',
    databaseURL: 'https://busarrivalalrammonitor-default-rtdb.firebaseio.com',
    storageBucket: 'busarrivalalrammonitor.appspot.com',
    measurementId: 'G-MYKNG7GBZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8Bj1vCBfPTS11iCJyrE-_Ox4cglRXjs',
    appId: '1:16582216303:android:ebb2abc2c0f1245e045b9a',
    messagingSenderId: '16582216303',
    projectId: 'busarrivalalrammonitor',
    databaseURL: 'https://busarrivalalrammonitor-default-rtdb.firebaseio.com',
    storageBucket: 'busarrivalalrammonitor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjPhGwqUkAqa28PJ-n8vjOsG5F5astbs',
    appId: '1:16582216303:ios:846a9a3ddf97fdbc045b9a',
    messagingSenderId: '16582216303',
    projectId: 'busarrivalalrammonitor',
    databaseURL: 'https://busarrivalalrammonitor-default-rtdb.firebaseio.com',
    storageBucket: 'busarrivalalrammonitor.appspot.com',
    iosBundleId: 'com.example.monitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjPhGwqUkAqa28PJ-n8vjOsG5F5astbs',
    appId: '1:16582216303:ios:846a9a3ddf97fdbc045b9a',
    messagingSenderId: '16582216303',
    projectId: 'busarrivalalrammonitor',
    databaseURL: 'https://busarrivalalrammonitor-default-rtdb.firebaseio.com',
    storageBucket: 'busarrivalalrammonitor.appspot.com',
    iosBundleId: 'com.example.monitorApp',
  );
}
